version: '3.9'
services:
  backend:
    build: 
      context: /root/projectbackend/backend-python/
      dockerfile: Dockerfile
    networks:
    - application
  frontend:
    build: 
      context: /root/projectfrontend/frontend-node/
      dockerfile: Dockerfile
    environment:
      BACKEND_URL: backend:8080
    networks:
    - application
    ports:
    - "9091:8080"
    depends_on:
    - backend
  mysql:
    image: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: kalsym@123
      MYSQL_DATABASE: php

volumes:
  mysql-volume:
networks:
  application:
    name: application
